name: FootJob
version: 6.0.0
main: Tungsten\FootJob\FootJob
api: 4.0.0
author: Tungsten,RealCatto 
authors:
  - RealCatto

permissions:
  footjob.permission:
    description: Allow to use footjob command
    default: op
